In [1]:
import cv2
import os
import numpy as np

In [2]:
#تعریف یک متغییر برای خواندن عکس های دیتاست

im = cv2.imread('10 Machine_Learning_Projects/Seasion 2(pardazesh pelak)/pelak/')

In [54]:
#چک کردن و مشاهده عکس

cv2.imshow('ax',im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [81]:
# استفاده کنیمlistdir برای خواندن کل عکس های یک فولد میتونید از دستور
files = os.listdir('1')

# با دستور پایین مسیر فایل به صورت دقیق تر مشخص میشه
#files = os.listdir('./1')

In [13]:
#کل فایل ها خوانده شد و داخل یک آرایه اضافه شدن!! 

print(files)

['3222.jpg', '3236.jpg', '348.jpg', '360.jpg', '374.jpg', '3168.jpg', '3154.jpg', '3140.jpg', '3197.jpg', '3183.jpg', '3342.jpg', '3343.jpg', '3182.jpg', '3196.jpg', '3141.jpg', '3155.jpg', '3169.jpg', '375.jpg', '361.jpg', '349.jpg', '3237.jpg', '3223.jpg', '3209.jpg', '3235.jpg', '3221.jpg', '388.jpg', '377.jpg', '363.jpg', '3143.jpg', '3157.jpg', '3180.jpg', '3194.jpg', '3341.jpg', '3340.jpg', '3195.jpg', '3181.jpg', '3156.jpg', '3142.jpg', '362.jpg', '376.jpg', '389.jpg', '3220.jpg', '3234.jpg', '3208.jpg', '3230.jpg', '3224.jpg', '3218.jpg', '399.jpg', '372.jpg', '366.jpg', '3146.jpg', '3152.jpg', '3185.jpg', '3191.jpg', '3344.jpg', '3345.jpg', '3190.jpg', '3184.jpg', '3153.jpg', '3147.jpg', '367.jpg', '373.jpg', '398.jpg', '3219.jpg', '3225.jpg', '3231.jpg', '3227.jpg', '3233.jpg', '365.jpg', '371.jpg', '359.jpg', '3151.jpg', '3145.jpg', '3179.jpg', '3192.jpg', '3186.jpg', '3346.jpg', '3187.jpg', '3193.jpg', '3178.jpg', '3144.jpg', '3150.jpg', '358.jpg', '370.jpg', '364.jpg', '32

In [44]:
#تمامی عکس های دیتاست با این دستور یک اندازه و یک سایز (8,32) میشن
im2 = cv2.resize(im,(8,32))

In [38]:
im2.shape

(32, 8, 3)

In [45]:
#برای دقیق تر شدن برنامه همه عکس هارو به خاکستری تبدیل میکنیم

im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)

In [41]:
#بعد سوم که برای نشون دادن رنگ ها بود کلا حذف شده

im3.shape

(32, 8)

In [46]:
print(im3)

[[ 29  35  34  36  44  36  40  37]
 [165 164 163 168 160 163 159 158]
 [175 179 177 175 172 174 175 176]
 [175 160 174 175 175 175 177 182]
 [170  42 170 178 178 181 142  50]
 [182  48 132 180 179 172  46  52]
 [157  53  72 175 179 187  53  39]
 [ 45  54  39 160 172 146  52  63]
 [ 39  52  63 141 198  55  56 119]
 [ 41  52  53  39  49  47  54 164]
 [ 41  54  51  57  50  55  47 182]
 [130  52  52  52  55  55  44 186]
 [159  53  56  53  56  62 157 183]
 [174  37  55  50  48  83 187 186]
 [178  33  54  46 129 188 183 186]
 [174  31  53  52 184 184 184 186]
 [173  65  52  73 186 184 185 186]
 [174  90  52  53 190 186 186 186]
 [186 110  60  56 187 186 186 186]
 [177 122  58  75 187 186 186 186]
 [185 124  56  70 189 186 187 187]
 [182 131  57  70 189 186 186 185]
 [183 121  56  87 189 185 185 186]
 [183 113  54 102 187 185 185 185]
 [183  98  57 118 187 185 185 185]
 [184  81  62 129 185 185 185 185]
 [184  65  51 145 184 184 185 185]
 [184 147 129 182 183 184 185 185]
 [183 184 182 184 18

In [4]:

#ارایه رو به یک بعدی تبدیل میکنیم که بتونیم هر یک پیکسل رو به عنوان ورودی به مدل بدیم 
im4 = im3.reshape(256)

#im4 = im3.flatten()

NameError: name 'im3' is not defined

In [50]:
print(im4)

[ 29  35  34  36  44  36  40  37 165 164 163 168 160 163 159 158 175 179
 177 175 172 174 175 176 175 160 174 175 175 175 177 182 170  42 170 178
 178 181 142  50 182  48 132 180 179 172  46  52 157  53  72 175 179 187
  53  39  45  54  39 160 172 146  52  63  39  52  63 141 198  55  56 119
  41  52  53  39  49  47  54 164  41  54  51  57  50  55  47 182 130  52
  52  52  55  55  44 186 159  53  56  53  56  62 157 183 174  37  55  50
  48  83 187 186 178  33  54  46 129 188 183 186 174  31  53  52 184 184
 184 186 173  65  52  73 186 184 185 186 174  90  52  53 190 186 186 186
 186 110  60  56 187 186 186 186 177 122  58  75 187 186 186 186 185 124
  56  70 189 186 187 187 182 131  57  70 189 186 186 185 183 121  56  87
 189 185 185 186 183 113  54 102 187 185 185 185 183  98  57 118 187 185
 185 185 184  81  62 129 185 185 185 185 184  65  51 145 184 184 185 185
 184 147 129 182 183 184 185 185 183 184 182 184 184 183 184 183 181 183
 180 181 183 184 177 178 184 186 179 183 181 185 17

In [51]:

im4.shape

(256,)

In [55]:
# برای دو بعدی کردن میتونیم از این دستور استفاده کنیم:

#im5 = im4.reshape(32,8)
#print(im5)

In [3]:
#تمامی تغییرات رو میتونیم داخل یم حلقه برای تمامی عکس های دیتاست انجام بدیم
files = os.listdir('1')

#ye array ba 256 vurudi dorost kardim ke x hammuno ja bedim tush
x = np.empty((0,256))
#ye array khali ham dorost kardim ke begim har x ei ke khundi y esh mishe masalan felan adad!!
y = np.array([])

for file_name in files:
    im = cv2.imread('1/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'1')

In [94]:
y[349]

'1'

In [4]:

x.shape

(350, 256)

In [5]:


files = os.listdir('2')

for file_name in files:
    im = cv2.imread('2/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'2')

In [8]:


files = os.listdir('3')

for file_name in files:
    im = cv2.imread('3/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'3')

In [10]:


files = os.listdir('4')

for file_name in files:
    im = cv2.imread('4/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'4')

In [12]:


files = os.listdir('5')

for file_name in files:
    im = cv2.imread('5/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'5')

In [14]:


files = os.listdir('6')

for file_name in files:
    im = cv2.imread('6/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'6')

In [16]:

files = os.listdir('7')

for file_name in files:
    im = cv2.imread('7/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'7')

In [18]:


files = os.listdir('8')

for file_name in files:
    im = cv2.imread('8/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'8')

In [20]:


files = os.listdir('9')

for file_name in files:
    im = cv2.imread('9/' + file_name)
    im2 = cv2.resize(im,(8,32))
    im3 = cv2.cvtColor(im2,cv2.COLOR_BGR2GRAY)
    im4 = im3.reshape(256)
    x=np.append(x,[im4],axis=0)
    y=np.append(y,'9')

In [24]:


y.shape

(3101,)